### ISSUE TITLE
Revising the typing system

### ISSUE THREAD

**Issue by SecondThundeR** [SecondThundeR/shikithon#14]
В данный момент, в некоторых местах библиотеки, типизация оставляет желать лучшего и после внедрения mypy, ситуация лишь стала более явной. Поэтому к версии 2.4 планирую переделать все проблемные места и внедрить некоторые улучшения для комфортной работы

> Вся работа по этому issue, ведётся в ветке [typing_rework](https://github.com/SecondThundeR/shikithon/tree/typing_rework)

### Roadmap
- Исправить всевозможные ошибки от mypy _(которых довольно дофига)_
<img width="548" alt="image" src="https://user-images.githubusercontent.com/36604233/221405105-a3ded1ee-82d1-46d4-9106-f280b5a7dfd3.png">

- ~Перевести все енамы на литералы~ (tl;dr https://github.com/SecondThundeR/shikithon/issues/14#issuecomment-1448484922)

- Убрать проверку на переданные строки енамов и вынести их для использования вне библиотеки

- _(Возможно)_ Использовать систему перегрузок для корректной работы выходных типов при разных аргументах

- _(Возможно)_ ~Избавиться каким-то образом от `Dict[str, Any]` и решить проблему с типизацией ответов от API~
> Тип возвращаемый методом `request` теперь `Optional[Union[Any, int]]`, где `None` и `int` используются для отсутствия значения и статуса кода, в то время как смена основного типа на `Any` сделана по той причине, что в основном данные респонза обрабатывают утилиты, и уже они разбираются как работать с ответом

### Прогресс

- [x] Исправить всевозможные ошибки от mypy
- [x] Убрать проверку на переданные строки енамов и вынести их для использования вне библиотеки
- [x] Использовать систему перегрузок для корректной работы выходных типов при разных аргументах
- ~Избавиться каким-то образом от `Dict[str, Any]` и решить проблему с типизацией ответов от API~ _(см. выше)_

**Comment by SecondThundeR** [comment]
Похоже переход на литералы был преждевременным, так как возникла проблема, что mypy странно проверяет, если в типе есть список литералов. Из-за этого, нельзя передать их другую функцию как строка, число и т.д.

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/36604233/221914759-83870ca4-e88e-4ec9-9749-2f661dbdad82.png">

В том же TypeScript подобная конструкция работает без нареканий

<img width="904" alt="image" src="https://user-images.githubusercontent.com/36604233/221915005-909caa9c-a0ff-4b86-95f9-27f5c5adeee6.png">

Переписывать большинство вспомогательных функций не хочется, поэтому скорее всего енамы будут возвращены, но теперь они будут вынесены для использования из вне библиотеки. Это уберет исходную проверку на переданные значения, которая была сделана на коленках, и заучивания возможных значений без автодополнения

> Коммиты с литералами были удалены (История: https://github.com/SecondThundeR/shikithon/compare/d47ebcc...775c631)

**Comment by ren3104** [comment]
Можно ещё доработать pydantic модели,  например модель для информации о клубе содержит не все поля.
